# Generated by Django 2.2 on 2020-08-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='new_state',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='todo_id',
            field=models.IntegerField(default=0),
        ),
    ]
