# Generated by Django 2.2 on 2020-08-13 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_auto_20200812_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='todo_id',
            new_name='todo_user_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='todo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='todo', to='lists.Todo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='marked',
            field=models.ManyToManyField(to='lists.User'),
        ),
    ]
