# Generated by Django 2.2 on 2020-08-13 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_auto_20200813_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='todo',
            new_name='todos',
        ),
    ]
