# Generated by Django 2.2 on 2020-08-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0007_auto_20200813_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='new_notif',
            field=models.IntegerField(default=0),
        ),
    ]
